### ISSUE TITLE
[ BUG ]

### ISSUE THREAD

**Issue by farhan403** [roogue/osu-collector-dl#6] opened 2022-12-04 11:57 UTC
**Describe**
When downloading big collections, the program does not finish downloading all the maps. After downloading about 500 filed from the collection, it just automatically closes without any warning and error or anything. The downloaded beatmaps are present in the folder but because it didn't download all of them, just closed on its own, only the ones it downloaded are present. FYI, the only thing I changed in the config file was changing the mode from 1 to 2 for the .osdb file.

**To Reproduce**
1. Download from the collection ...
2. Wait until the error occurs

**Error log (If present):**
```
===Some Error===
```

**Expected behavior**
I just expected the download to finish and the window to normally say that the download is finished and press Enter to exit.

**Screenshots**

**Additional information:**
- Operating System: [e.g. iOS]

**Additional context**
The collections I was trying to download were-
https://osucollector.com/collections/6059
https://osucollector.com/collections/488

**Comment by roogue** [comment] 2022-12-04 12:08
Thanks for the report, I will look into it when I am free.

**Temporary Solution:**
For temporary solution to your issue, you can try to download the rest of them through Collection Manager (CM).

In CM, Click "Online" at the navigation bar, then click "Download all missing maps".

Apologize for the inconvenience caused :(

**Comment by farhan403** [comment] 2022-12-04 14:27
Thank you so much and you don't need to apologize or something because
you're already making the downloading process from osucollection so
much easier. Thank you again.

**Comment by roogue** [comment] 2023-01-06 04:39
Hi Farhan, sorry that I was unable to reproduce your situation as I am able to download all of them without the terminal closing itself on the version v2.6.4. It's okay, I will test it on different devices and condition and see how things might go.

**Additional Information:**
v2.6.4 was tested and confirmed that some beatmaps are not correctly downloaded, please switch to the current latest version (v.2.6.5) for best functionality.

**Closed** 2023-01-06 04:40 UTC
Labels: bug

**Comment by farhan403** [comment] 2023-01-16 17:58
Ok, thanks.
